#123456789012345678901234567890123456789012345678901234567890123456789012345678
"""This module contains helper functions to prepare data for analysis."""

import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader


def time_series_split(df, test_start_date, buffer_size, date_col='date'):
    """Splits DataFrame into train/test splits with buffer in between.

    Keyword arguments:
      df -- Pandas DataFrame
      test_start_date -- str for start date of test split: 'YYYY-MM-DD'
      buffer_size -- number of business days between end of train split and 
                     beginning of test split
    """
    assert date_col in df.columns, f'date column "{date_col}" not in DataFrame'
    test_df = df[df[date_col] >= test_start_date]
    train_df = df[df[date_col] < test_start_date][:-buffer_size]
    return train_df.copy(), test_df.copy()


def remove_series(df, tickers_to_remove=None):
    """Removes data and labels for a financial asset from a DataFrame.
    
    Keyword arguments:
      df -- Pandas DataFrame
      tickers_to_remove -- list of ticker symbols to be removed from df
    Return:
      df -- DataFrame with all columns containing listed tickers removed
    """
    assert type(df) == type(pd.DataFrame()), 'df must be a DataFrame'
    if tickers_to_remove is not None:
        for ticker in tickers_to_remove:
            for column_name in df.columns:
                if ticker in column_name:
                    df = df.drop(columns=[column_name]).copy()
    return df


def get_X_y_cols(df, label_marker='target'):
    """Creates separate lists of column names for data features and labels.

    Keyword arguments:
      df -- Pandas DataFrame containing labelled data
      label_marker -- str that is part of a column name for a label
    Return:
      (feature_columns, label_columns) -- tuple of lists of column names
    """
    assert type(df) == type(pd.DataFrame()), 'df must be a DataFrame'
    feature_columns, label_columns = [], []
    for column_name in df.columns:
        if label_marker in column_name:
            label_columns.append(column_name)
        else:
            if ('target' not in column_name) and (column_name != 'date'):
                feature_columns.append(column_name)
    return (feature_columns, label_columns)


# -----------------------------------------------------------------------------
# Datasets:
#   A. UnivariateTimeSeriesDataset -- a basic dataset for time series data
#   B. FinancialDataset -- a custom dataset for predicting asset volatility
# -----------------------------------------------------------------------------


class UnivariateTimeSeriesDataset(Dataset):
    """Dataset for univariate time series data.
    
    This dataset implements a backward-looking rolling window to generate
    feature vectors consisting of successive values in a time series.
    In this implementation, the label for each feature vector is the value of
    the sample (sequence) at the next time step.
    """
    
    def __init__(self, data, window_size):
        """Create a Dataset from time series data (x = f(t)).

        Keyword arguments:
          data -- Numpy Array containing the values of the series
          window_size -- number of timestamps in the rolling window
        """
        self.data = torch.from_numpy(data.copy())
        self.window_size = window_size

    def __len__(self):
        return len(self.data) - self.window_size

    def __getitem__(self, idx):
        """Generate a univariate feature vector (x_i) and its label (y_i).
        
        The feature vector (x_i) is a sequence of successive values for the time series,
        generated by a backward-looking window.  The label is simply the value of the time 
        series at the next timestamp after the window.
        """
        x_i = self.data[idx : idx + self.window_size]
        y_i = self.data[idx + self.window_size]
        # Reshape values as required for PyTorch DataLoader implementation
        return x_i.reshape(-1, 1), y_i.reshape(1)


class FinancialDataset(Dataset):
    """Dataset for time series financial data."""
    
    def __init__(self, data, labels, window_size=63):
        """Create a Dataset from time series data (X) and labels (y).

        Keyword arguments:
          data -- NumPy array of shape = (num_timestamps, feature_dim)
          labels -- NumPy array of shape = (num_timestamps, label_dim)
          window_size -- length of each sequence generated by a rolling window
        """
        assert len(data) == len(labels),\
            'data (X) and labels (y) must be same length'
        self.data = torch.from_numpy(data.copy())
        self.labels = torch.from_numpy(labels.copy())
        self.window_size = window_size
        self.X_dim = data.shape[-1]  # Number of features in data sample
        self.y_dim = labels.shape[-1]  # Number of features in label

    def __len__(self):
        return len(self.data) - self.window_size

    def __getitem__(self, idx):
        """Retreive a sample (X_i) and its label (y_i).
        
        We rely on a (slightly flawed) financial theory that historical
        observations are useful in predicting future values of return 
        and volatility.
         - Therefore, each data sample (X_i) is a matrix consisting of a
           series (length of series = window_size) of past observations,
           where each observation is a row vector of dimension (X_dim).
         - Each label (y_i) is a row vector containing the computed
           future values of (return, volatility) for each ETF in the data
           sample, as of the timestamp at the end of the rolling window.
        ------------------
        Keyword arguments:
          idx -- starting index for the data sample
        Returns:
          X_i -- PyTorch tensor of shape (window_size, X_dim)
          y_i -- PyTorch tensor of shape (y_dim)
        """
        # Note: (3-16-2026) May need to reshape the output!!
        X_i = self.data[idx : idx + self.window_size]
        y_i = self.labels[idx + self.window_size - 1]
        return X_i, y_i
        